[project]
name = "sre-take-home-exercise-python"
version = "0.1.0"
description = "Fetch Python Exercise"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
